baseURL = 'https://derpen.xyz/'
languageCode = 'en-us'
title = "dpn's stuff"
theme = 'ananke'
enableRobotsTXT = true
 
[params]
  text_color = ""
  author = ""
  favicon = "/images/resource/Puck_minimap_icon.webp"
  site_logo = "/images/resource/Puck_minimap_icon.webp"
  description = "It's my personal web page :3"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
 
[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/muhammad-rizqi-assabil/"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/derpen"
